
import "./globals.css";
import {Toaster,toast} from 'react-hot-toast'
import Navbar from "./components/navbar";



export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased text-gray-500 capitalize`}
      >  
        <Toaster />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
